services:
    database:
        container_name: database

        build:
            context: ./mysql
            dockerfile: Dockerfile

        volumes:
            - ./mysqldb:/var/lib/mysql

        environment:
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=root

        networks:
            - bridge-network

    node:
        container_name: node

        entrypoint: dockerize -wait tcp://database:3306 node index.js

        volumes:
            - ./node:/app
            - /app/node_modules

        build:
            context: ./node
            dockerfile: Dockerfile

        networks:
            - bridge-network

        ports:
            - 3000:3000

        depends_on:
            - database

    nginx:
        container_name: nginx

        build:
            context: ./nginx
            dockerfile: Dockerfile

        networks:
            - bridge-network

        ports:
            - "8080:80"

        depends_on:
            - node

networks:
    bridge-network:
        driver: bridge
